Developer
ash-jc-allen/laravel-executor pull request #14
Opened 2020-10-03 13:28 UTC by arefeh-rj

2020-10-03 17:05 UTC, ash-jc-allen commented
Hi @arefeh-rj , could you please correct the styling for this pull request? If you'd prefer to use this pull request, you can close your existing one :)

2020-10-03 17:25 UTC, arefeh-rj commented
Ok
I closed the first request 👌😊

On Sat, Oct 3, 2020, 20:35 Ash Allen <notifications@github.com> wrote:

> Hi @arefeh-rj <https://github.com/arefeh-rj> , could you please correct
> the styling for this pull request? If you'd prefer to use this pull
> request, you can close your existing one :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ash-jc-allen/laravel-executor/pull/14#issuecomment-703133916>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQTLMVHHYNQJRYTURNDPZVTSI5KVDANCNFSM4SCVCYFQ>
> .
>

2020-10-04 05:54 UTC, arefeh-rj commented
Hi @ash-jc-allen 
check the styling for the pull request :)

2020-10-04 12:37 UTC, ash-jc-allen requested changes

2020-10-04 12:37 UTC, ash-jc-allen commented on src/Classes/Executor.php
> +     * @param NotifierFactory|null $notifierFactory
It seems like there's still a lot of comments and docblocks that have been updated. Please could you revert all these back to how they were?

2020-10-04 12:37 UTC, ash-jc-allen commented on src/Classes/Executor.php
> +    public function runArtisan(string $command, bool $isInteractive = false, ?float $timeOut = 60): self
Rather than ``` ?float $timeOut = 60 ```, I think we'd be better off with ``` float $timeOut = 60 ``` :)

2020-10-04 12:37 UTC, ash-jc-allen commented on src/Classes/Executor.php
> +    public function runExternal(string $command, bool $isInteractive = false, ?float $timeOut = 60): self
Rather than ``` ?float $timeOut = 60``` , I think we'd be better off with ``` float $timeOut = 60 ``` :)

2020-10-04 12:37 UTC, ash-jc-allen commented on src/Classes/Executor.php
> +    public function runArtisan(string $command, bool $isInteractive = false, ?float $timeOut = 60): self
You'll also need to add the new parameter to the docblock above as well

2020-10-04 12:37 UTC, ash-jc-allen commented on src/Classes/Executor.php
> +        $process->setTimeout($timeOut);
Could you please add a blank line between line 148 and 149?

2020-10-04 12:37 UTC, ash-jc-allen commented on src/Classes/Executor.php
> +    private function runCommand(string $commandToRun, bool $isInteractive = false, ?float $timeOut = 60): void
Rather than ``` ?float $timeOut = 60 ```, I think we'd be better off with ``` float $timeOut = 60 ``` :)

2020-10-05 17:54 UTC, ash-jc-allen approved these changes
Thanks for making these changes! I'll get them pulled in now and try to get it ready for release over the next day or two! :smile:

2020-10-05 17:54 UTC, merged

2020-10-05 21:35 UTC, ash-jc-allen commented
This feature has now been added into the v2.1.0 release (https://github.com/ash-jc-allen/laravel-executor/releases/tag/v2.1.0).

2020-10-06 07:52 UTC, arefeh-rj commented
thanks :)

On Tue, Oct 6, 2020 at 1:05 AM Ash Allen <notifications@github.com> wrote:

> This feature has now been added into the v2.1.0 release (
> https://github.com/ash-jc-allen/laravel-executor/releases/tag/v2.1.0).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ash-jc-allen/laravel-executor/pull/14#issuecomment-703902017>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQTLMVAXN4H5E6FVXKJAOBLSJI3Z3ANCNFSM4SCVCYFQ>
> .
>